### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by balibou** [GiladShoham/graphql-apollo-errors#2]
Awesome package !

Is it possible to get a working example, because I set up all the config from the README, and I still have an error on the browser like this:

<img width="475" alt="screen shot 2017-03-03 at 17 54 06" src="https://cloud.githubusercontent.com/assets/7440159/23562465/77260ef4-003a-11e7-9a9b-3acb1b743414.png">

**Comment by GiladShoham** [comment]
Thanks @balibou ,
It looks like a problem on the client side.
Can you please show me what you get in the network tab in the developer tools?

**Comment by GiladShoham** [comment]
Close due to inactivity
